# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa63dd7bf9dce23991ef8533c44369dc1b86a09c99b2bd8b1c5d80a7706effc72974b0f7f783dcd2cfcdb9ab02aee54ce3123fc3d9a9ec1ec645d35d9c15fe91

test:
  secret_key_base: 7ad07601fc606177a7a4315f3cd49e89382eebcc33164c22d08f6502edb3b12bb80bd5492049773fa966c24db763731a5effcc15df3123b6c56e5f6de5643f52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
